'use client';
import {useEffect,useMemo,useState} from 'react';
import {ChevronDown,ChevronRight,LogOut,Truck,Users,CalendarDays,Upload,ClipboardList} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Role='ADMIN'|'DISPATCHER'|'EXECUTOR'|'CONTROLLER';
const dayNames=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'];
const uiMonths=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];
function App(){const [session,setSession]=useState<any>(null);const [profile,setProfile]=useState<any>(null);const [page,setPage]=useState('schedule');const [loading,setLoading]=useState(true);useEffect(()=>{supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session)await loadProfile(data.session.user.id);setLoading(false)});const {data}=supabase.auth.onAuthStateChange(async(_,s)=>{setSession(s);if(s)await loadProfile(s.user.id);else setProfile(null)});return()=>data.subscription.unsubscribe()},[]);async function loadProfile(id:string){const {data}=await supabase.from('users').select('*').eq('id',id).maybeSingle();setProfile(data)}if(loading)return <div className="login">Memuat Movent…</div>;if(!session)return <Login/>;return <Dashboard profile={profile} page={page} setPage={setPage}/>}
function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [err,setErr]=useState('');const [busy,setBusy]=useState(false);async function submit(e:any){e.preventDefault();setBusy(true);setErr('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setErr('Email atau kata sandi tidak valid.');setBusy(false)}return <main className="login"><form className="loginbox" onSubmit={submit}><div style={{fontSize:24,fontWeight:700}}>MOVENT</div><div className="muted">Movement Management</div>{err&&<div className="error">{err}</div>}<div className="field"><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="nama@movent.id" autoComplete="username"/></div><div className="field"><label>Kata Sandi</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></div><button className="btn primary" style={{width:'100%'}} disabled={busy}>{busy?'Masuk…':'Masuk'}</button><div className="footer" style={{color:'#64748b',padding:'18px 0 0'}}>Part of FTC Go Project<br/>Developed by Fleet Traffic Control</div></form></main>}
function Dashboard({profile,page,setPage}:{profile:any,page:string,setPage:(x:string)=>void}){const role:Role=profile?.role||'DISPATCHER';const nav=[['schedule','Schedule',CalendarDays],...(role==='EXECUTOR'?[['tasks','Tugas',ClipboardList]]:[['assignment','Assignment',Truck],['master','Master Data',Users],['upload','Upload Data',Upload]])] as any[];return <div className="app"><div className="shell"><aside className="side"><div className="brand">MOVENT</div><div className="nav">{nav.map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><I size={16} style={{verticalAlign:'middle',marginRight:9}}/>{label}</button>)}</div><div className="footer">Part of FTC Go Project<br/><b>Developed by Fleet Traffic Control</b></div></aside><main className="content">{page==='schedule'?<Schedule/>:page==='assignment'?<Assignment/>:page==='master'?<Master/>:page==='upload'?<UploadPage/>:<Tasks/>}</main></div><div className="mobilebar">{nav.map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><I size={16}/><br/>{label}</button>)}<button onClick={()=>supabase.auth.signOut()}><LogOut size={16}/><br/>Keluar</button></div></div>}
function Schedule(){const [date,setDate]=useState(new Date());const [movement,setMovement]=useState<'OTB'|'INB'>('OTB');const [rows,setRows]=useState<any[]>([]);const [q,setQ]=useState('');const [open,setOpen]=useState<Record<string,boolean>>({});useEffect(()=>{load()},[date,movement]);async function load(){const {data}=await supabase.from('schedules').select('id,schedule_code,schedule_date,start_point,destination,std,sta,hubs(name)').eq('schedule_date',date.toISOString().slice(0,10)).eq('movement_type',movement).order('std');setRows(data||[])}const filtered=rows.filter(r=>`${r.schedule_code} ${r.start_point} ${r.destination}`.toLowerCase().includes(q.toLowerCase()));const groups=useMemo(()=>filtered.reduce((a:any,x:any)=>{const k=x.hubs?.name||'Tanpa Hub';(a[k]??=[]).push(x);return a},{}),[filtered]);const shift=(n:number)=>setDate(d=>new Date(d.getTime()+n*86400000));return <><div className="top"><div><div className="title">Schedule</div><div className="muted">{dayNames[date.getDay()]}, {date.getDate()} {uiMonths[date.getMonth()]}</div></div><button className="btn secondary" onClick={()=>supabase.auth.signOut()}>Keluar</button></div><div className="card"><div className="toolbar"><div className="day"><button onClick={()=>shift(-1)}>‹</button><b>{date.toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'short'})}</b><button onClick={()=>shift(1)}>›</button></div><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari Schedule ID, asal, tujuan"/></div><div className="tabs"><button className={'tab '+(movement==='OTB'?'on':'')} onClick={()=>setMovement('OTB')}>OTB</button><button className={'tab '+(movement==='INB'?'on':'')} onClick={()=>setMovement('INB')}>INB</button></div>{Object.keys(groups).map(h=><div className="hub" key={h}><div className="hubhead" onClick={()=>setOpen(o=>({...o,[h]:o[h]===false}))}>{open[h]===false?<ChevronRight size={17}/>:<ChevronDown size={17}/>}<span style={{flex:1}}>{h}</span><span className="muted">{groups[h].length}</span></div>{open[h]!==false&&<div className="tablewrap"><table className="table"><thead><tr><th>Schedule ID</th><th>Start Point</th><th>Destination</th><th>STD</th><th>STA</th><th>Duration</th></tr></thead><tbody>{groups[h].map((r:any)=><tr key={r.id}><td><b>{r.schedule_code}</b></td><td>{r.start_point}</td><td>{r.destination}</td><td>{String(r.std).slice(0,5)}</td><td>{String(r.sta).slice(0,5)}</td><td>{duration(r.std,r.sta)}</td></tr>)}</tbody></table></div>}</div>)}{!rows.length&&<div className="muted" style={{padding:20,textAlign:'center'}}>Tidak ada schedule untuk hari dan tipe ini.</div>}</div></>}
function duration(a:string,b:string){const [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number);let x=bh*60+bm-(ah*60+am);if(x<0)x+=1440;return `${Math.floor(x/60)}j ${x%60}m`}
function Assignment(){return <div><div className="title">Assignment</div><div className="muted" style={{marginBottom:18}}>Layer tugas di atas schedule.</div><div className="card">Pilih schedule dari halaman Schedule untuk membuat assignment.</div></div>}
function Master(){return <div><div className="title">Master Data</div><div className="muted" style={{marginBottom:18}}>Data referensi operasional.</div><div className="card">Fleet, Executor, Produk, dan Hub dikelola melalui data master.</div></div>}
function UploadPage(){return <div><div className="title">Upload Data</div><div className="muted" style={{marginBottom:18}}>Upload → validasi → preview → konfirmasi → import.</div><div className="card"><div className="field"><label>Jenis Data</label><select><option>Executor</option><option>Fleet</option><option>Product</option><option>Schedule</option><option>User Login</option></select></div><div className="field"><label>File CSV</label><input type="file" accept=".csv"/></div><button className="btn primary">Validasi File</button></div></div>}
function Tasks(){return <div><div className="title">Tugas Saya</div><div className="muted" style={{marginBottom:18}}>Task yang ditugaskan kepada Anda.</div><div className="card">Belum ada task.</div></div>}
export default App;
