'use client';

import {useEffect,useMemo,useState} from 'react';
import {Download,FileSpreadsheet,FileText,RefreshCw,Search} from 'lucide-react';
import {supabase} from '../../lib/supabase';
import * as XLSX from 'xlsx';

type Row={id:string;assignment_no:string;schedule_id:string;schedule_day_name:string;schedule_hub_id:string;schedule_route:string;schedule_category:string;start_point:string;destination:string;plat_number:string;executor_nik:string;std:string;sta:string;status:string;created_at:string;accepted_at:string|null;departed_at:string|null;arrived_at:string|null;completed_at:string|null;start_odometer:number|null;end_odometer:number|null;total_distance:number|null;report_date:string};
const statuses=['ALL','ASSIGNED','CONFIRMED','IN_PROGRESS','ARRIVED','COMPLETED','CANCELLED'];
function today(){return new Date().toLocaleDateString('en-CA')}
function fmt(t:string|null){return t?new Date(t).toLocaleString('id-ID',{dateStyle:'short',timeStyle:'short'}):'—'}
function safeCell(v:any){const s=String(v??'');return /^[=+\\-@]/.test(s)?`'${s}`:s}
function rowsForExport(rows:Row[]){return rows.map(r=>({
  'Tanggal Report':r.report_date,'Assignment':r.assignment_no,'Schedule ID':r.schedule_id,'Day':r.schedule_day_name,'Hub':r.schedule_hub_id,'Route':r.schedule_route,'Category':r.schedule_category,'Start Point':r.start_point,'Destination':r.destination,'Fleet':r.plat_number,'Executor NIK':r.executor_nik,'STD':String(r.std).slice(0,5),'STA':String(r.sta).slice(0,5),'Status':r.status,'Created':fmt(r.created_at),'Confirmed':fmt(r.accepted_at),'Departed':fmt(r.departed_at),'Arrived':fmt(r.arrived_at),'Completed':fmt(r.completed_at),'Start ODO':r.start_odometer??'','End ODO':r.end_odometer??'','Total Distance':r.total_distance??''
})).map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,safeCell(v)])))}
function csvEscape(v:any){const s=String(v??'');return /[",\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function downloadCsv(rows:Row[],name:string){const data=rowsForExport(rows);const headers=Object.keys(data[0]||{});const csv='\\uFEFF'+[headers.map(csvEscape).join(','),...data.map(r=>headers.map(h=>csvEscape(r[h])).join(','))].join('\\r\\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();URL.revokeObjectURL(url)}
function downloadXlsx(rows:Row[],name:string){const ws=XLSX.utils.json_to_sheet(rowsForExport(rows));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Report');XLSX.writeFile(wb,name+'.xlsx')}

export default function ControllerPage(){
 const [authorized,setAuthorized]=useState(false);const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const [startDate,setStartDate]=useState(today());const [endDate,setEndDate]=useState(today());const [status,setStatus]=useState('ALL');const [q,setQ]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{if(!data.session){window.location.href='/';return}const {data:p}=await supabase.from('profiles').select('role,status,is_locked').eq('id',data.session.user.id).maybeSingle();if(!p||p.status!=='Active'||p.is_locked||!['Controller','Super User'].includes(p.role)){window.location.href='/';return}setAuthorized(true)});},[]);
 async function load(){setError('');setRows([]);if(!startDate||!endDate){setError('Tanggal mulai dan tanggal akhir wajib diisi.');return}if(startDate>endDate){setError('Tanggal mulai tidak boleh lebih besar dari tanggal akhir.');return}setLoading(true);const {data,error}=await supabase.rpc('controller_report',{p_start_date:startDate,p_end_date:endDate,p_status:status==='ALL'?null:status});if(error)setError(error.message);else setRows((data||[]) as Row[]);setLoading(false)}
 const filtered=useMemo(()=>{const term=q.trim().toLowerCase();if(!term)return rows;return rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(term)))},[rows,q]);
 const exportName=`movent-report-${startDate}-to-${endDate}-${status.toLowerCase()}`;
 if(!authorized)return <div className="login">Memuat Movent…</div>;
 return <div><div className="top"><div><div className="title">Controller Report</div><div className="muted">Tarik data operasional Dispatcher + Executor berdasarkan rentang waktu dan status.</div></div><button className="btn secondary" onClick={load} disabled={loading}><RefreshCw size={15} style={{marginRight:7,verticalAlign:'middle'}}/>{loading?'Menarik…':'Tarik Report'}</button></div>
 <div className="card" style={{marginBottom:16}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr auto',gap:12,alignItems:'end'}}><div className="field"><label>Tanggal Mulai</label><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></div><div className="field"><label>Tanggal Akhir</label><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></div><div className="field"><label>Status</label><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s} value={s}>{s==='ALL'?'All Status':s}</option>)}</select></div><button className="btn primary" onClick={load} disabled={loading}>{loading?'Menarik…':'Tarik Report'}</button></div></div>
 {error&&<div className="error" style={{marginBottom:12}}>{error}</div>}
 <div className="card"><div className="toolbar"><div style={{fontWeight:700}}>Hasil Report <span className="muted">· {filtered.length} data</span></div><div style={{display:'flex',gap:8,alignItems:'center',flex:1,justifyContent:'flex-end'}}><div style={{position:'relative',minWidth:220,maxWidth:320,flex:1}}><Search size={15} style={{position:'absolute',left:10,top:10,color:'#64748b'}}/><input className="search" style={{width:'100%',paddingLeft:32}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari hasil report…"/></div><button className="btn secondary" onClick={()=>downloadCsv(filtered,exportName)} disabled={!filtered.length}><FileText size={15} style={{marginRight:6,verticalAlign:'middle'}}/>CSV</button><button className="btn secondary" onClick={()=>downloadXlsx(filtered,exportName)} disabled={!filtered.length}><FileSpreadsheet size={15} style={{marginRight:6,verticalAlign:'middle'}}/>XLSX</button></div></div>
 <div className="tablewrap"><table className="table"><thead><tr><th>Tanggal</th><th>Assignment</th><th>Schedule</th><th>Hub</th><th>Route</th><th>Fleet</th><th>Executor</th><th>STD/STA</th><th>Status</th><th>Actual</th><th>ODO</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.report_date}</td><td><b>{r.assignment_no}</b><br/><span className="muted">{r.schedule_category}</span></td><td>{r.schedule_id}<br/><span className="muted">{r.schedule_day_name}</span></td><td>{r.schedule_hub_id}</td><td>{r.schedule_route}<br/><span className="muted">{r.start_point} → {r.destination}</span></td><td>{r.plat_number}</td><td>{r.executor_nik}</td><td>{String(r.std).slice(0,5)} / {String(r.sta).slice(0,5)}</td><td><b>{r.status}</b></td><td><div>C {fmt(r.accepted_at)}</div><div>D {fmt(r.departed_at)}</div><div>A {fmt(r.arrived_at)}</div><div>F {fmt(r.completed_at)}</div></td><td>{r.start_odometer??'—'} → {r.end_odometer??'—'}<br/><span className="muted">Total {r.total_distance??'—'}</span></td></tr>)}</tbody></table></div>{!loading&&!filtered.length&&<div className="muted" style={{padding:20,textAlign:'center'}}>{rows.length?'Data tidak ditemukan sesuai pencarian.':'Belum ada hasil. Atur filter lalu klik Tarik Report.'}</div>}</div>
 <div className="muted" style={{fontSize:12,marginTop:10}}>Report hanya read-only. Data yang sudah dihapus oleh retention 90 hari tidak dapat ditarik kembali.</div></div>
}
