-- Movent v2.1 baseline schema and workflow functions.
-- Applied to Supabase project rufvogaxmepezotkbgug.
-- Schedule remains operationally read-only; state transitions are backend functions.

create extension if not exists pgcrypto;
create type public.user_role as enum ('ADMIN','DISPATCHER','EXECUTOR','CONTROLLER');
create type public.movement_type as enum ('OTB','INB');
create type public.assignment_status as enum ('ASSIGNED','CONFIRMED','IN_PROGRESS','ARRIVED','COMPLETED','CANCELLED');

create table if not exists public.users (id uuid primary key references auth.users(id) on delete cascade,email text not null unique,full_name text not null,role public.user_role not null,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.executors (id uuid primary key default gen_random_uuid(),user_id uuid unique references public.users(id) on delete set null,nik text not null unique,full_name text not null,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.fleets (id uuid primary key default gen_random_uuid(),plate_number text not null unique,fleet_type text not null,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(),product text not null unique,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.hubs (id uuid primary key default gen_random_uuid(),name text not null unique,code text not null unique,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.import_batches (id uuid primary key default gen_random_uuid(),source_file text not null,data_type text not null,imported_by uuid references public.users(id) on delete set null,imported_at timestamptz not null default now(),status text not null,summary jsonb,error_info jsonb);
create table if not exists public.schedules (id uuid primary key default gen_random_uuid(),schedule_code text not null unique,schedule_date date not null,movement_type public.movement_type not null,hub_id uuid not null references public.hubs(id),start_point text not null,destination text not null,std time not null,sta time not null,import_batch_id uuid references public.import_batches(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.assignments (id uuid primary key default gen_random_uuid(),schedule_id uuid not null references public.schedules(id),fleet_id uuid not null references public.fleets(id),executor_id uuid not null references public.executors(id),status public.assignment_status not null default 'ASSIGNED',created_by uuid not null references public.users(id),created_at timestamptz not null default now(),confirmed_at timestamptz,confirmed_by uuid references public.users(id),cancelled_at timestamptz,cancelled_by uuid references public.users(id),cancel_reason text,updated_at timestamptz not null default now());
create table if not exists public.surat_jalans (id uuid primary key default gen_random_uuid(),assignment_id uuid not null references public.assignments(id) on delete cascade,nomor_sj text not null,qty numeric not null,berat numeric not null,produk text not null,catatan text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.execution (id uuid primary key default gen_random_uuid(),assignment_id uuid not null unique references public.assignments(id) on delete cascade,odometer_awal numeric,odometer_awal_at timestamptz,odometer_akhir numeric,odometer_akhir_at timestamptz,received_at timestamptz,sj_confirmed_at timestamptz,departed_at timestamptz,arrived_at timestamptz,completed_at timestamptz,updated_at timestamptz not null default now());
create table if not exists public.activity_logs (id uuid primary key default gen_random_uuid(),assignment_id uuid references public.assignments(id) on delete cascade,actor_user_id uuid references public.users(id) on delete set null,event_type text not null,event_at timestamptz not null default now(),metadata jsonb);
create index if not exists schedules_operational_idx on public.schedules(schedule_date,movement_type,hub_id,std);
create index if not exists assignments_executor_status_idx on public.assignments(executor_id,status);
create index if not exists activity_logs_assignment_event_idx on public.activity_logs(assignment_id,event_at);

create or replace function public.current_user_role() returns public.user_role language sql stable security definer set search_path=public as $$ select role from public.users where id=auth.uid() and is_active=true limit 1 $$;
create or replace function public.is_admin_or_dispatcher() returns boolean language sql stable security definer set search_path=public as $$ select public.current_user_role() in ('ADMIN','DISPATCHER') $$;
create or replace function public.is_executor() returns boolean language sql stable security definer set search_path=public as $$ select public.current_user_role()='EXECUTOR' $$;

alter table public.users enable row level security;
alter table public.executors enable row level security;
alter table public.fleets enable row level security;
alter table public.products enable row level security;
alter table public.hubs enable row level security;
alter table public.import_batches enable row level security;
alter table public.schedules enable row level security;
alter table public.assignments enable row level security;
alter table public.surat_jalans enable row level security;
alter table public.execution enable row level security;
alter table public.activity_logs enable row level security;

create policy users_self_or_admin on public.users for select using (id=auth.uid() or public.current_user_role()='ADMIN');
create policy users_admin_write on public.users for all using (public.current_user_role()='ADMIN') with check (public.current_user_role()='ADMIN');
create policy executors_read_authorized on public.executors for select using (public.is_admin_or_dispatcher() or user_id=auth.uid());
create policy fleets_read_authorized on public.fleets for select using (public.is_admin_or_dispatcher());
create policy products_read_authorized on public.products for select using (public.is_admin_or_dispatcher() or public.is_executor());
create policy hubs_read_authorized on public.hubs for select using (public.is_admin_or_dispatcher() or public.is_executor());
create policy schedules_read_authorized on public.schedules for select using (public.is_admin_or_dispatcher() or public.is_executor());
create policy assignments_dispatcher_read on public.assignments for select using (public.is_admin_or_dispatcher());
create policy assignments_executor_read on public.assignments for select using (public.is_executor() and executor_id in (select id from public.executors where user_id=auth.uid()));
create policy assignments_dispatcher_insert on public.assignments for insert with check (public.is_admin_or_dispatcher() and created_by=auth.uid());
create policy assignments_dispatcher_update on public.assignments for update using (public.is_admin_or_dispatcher() and status='ASSIGNED') with check (public.is_admin_or_dispatcher());
create policy assignments_executor_confirm on public.assignments for update using (public.is_executor() and executor_id in (select id from public.executors where user_id=auth.uid()) and status='ASSIGNED') with check (public.is_executor() and executor_id in (select id from public.executors where user_id=auth.uid()) and status='CONFIRMED');
create policy sj_authorized_read on public.surat_jalans for select using (public.is_admin_or_dispatcher() or assignment_id in (select id from public.assignments where executor_id in (select id from public.executors where user_id=auth.uid())));
create policy sj_executor_insert on public.surat_jalans for insert with check (public.is_executor() and assignment_id in (select id from public.assignments where executor_id in (select id from public.executors where user_id=auth.uid()) and status='CONFIRMED'));
create policy sj_executor_update on public.surat_jalans for update using (public.is_executor() and assignment_id in (select id from public.assignments where executor_id in (select id from public.executors where user_id=auth.uid()) and status='CONFIRMED')) with check (true);
create policy sj_executor_delete on public.surat_jalans for delete using (public.is_executor() and assignment_id in (select id from public.assignments where executor_id in (select id from public.executors where user_id=auth.uid()) and status='CONFIRMED'));
create policy execution_authorized_read on public.execution for select using (public.is_admin_or_dispatcher() or assignment_id in (select id from public.assignments where executor_id in (select id from public.executors where user_id=auth.uid())));
create policy execution_executor_insert on public.execution for insert with check (public.is_executor() and assignment_id in (select id from public.assignments where executor_id in (select id from public.executors where user_id=auth.uid())));
create policy execution_executor_update on public.execution for update using (public.is_executor() and assignment_id in (select id from public.assignments where executor_id in (select id from public.executors where user_id=auth.uid()))) with check (true);
create policy logs_authorized_read on public.activity_logs for select using (public.is_admin_or_dispatcher() or assignment_id in (select id from public.assignments where executor_id in (select id from public.executors where user_id=auth.uid())));
create policy logs_insert_authenticated on public.activity_logs for insert with check (auth.uid()=actor_user_id);

-- Workflow RPCs are the enforcement layer for executor state changes.
create or replace function public.confirm_assignment(p_assignment_id uuid) returns public.assignments language plpgsql security definer set search_path=public as $$ declare r public.assignments; begin select * into r from public.assignments where id=p_assignment_id for update; if r.id is null or r.status <> 'ASSIGNED' then raise exception 'Invalid assignment state'; end if; if not exists(select 1 from public.executors where id=r.executor_id and user_id=auth.uid() and is_active) then raise exception 'Not your assignment'; end if; update public.assignments set status='CONFIRMED',confirmed_at=now(),confirmed_by=auth.uid(),updated_at=now() where id=p_assignment_id returning * into r; insert into public.execution(assignment_id,received_at) values(p_assignment_id,now()) on conflict(assignment_id) do update set received_at=excluded.received_at,updated_at=now(); return r; end $$;
create or replace function public.confirm_surat_jalan(p_assignment_id uuid) returns public.execution language plpgsql security definer set search_path=public as $$ declare e public.execution; begin if not exists(select 1 from public.assignments a join public.executors x on x.id=a.executor_id where a.id=p_assignment_id and a.status='CONFIRMED' and x.user_id=auth.uid()) then raise exception 'Invalid task state'; end if; if not exists(select 1 from public.surat_jalans where assignment_id=p_assignment_id) then raise exception 'At least one Surat Jalan is required'; end if; update public.execution set sj_confirmed_at=now(),updated_at=now() where assignment_id=p_assignment_id returning * into e; if e.id is null then raise exception 'Execution not initialized'; end if; insert into public.activity_logs(assignment_id,actor_user_id,event_type) values(p_assignment_id,auth.uid(),'SJ_CONFIRMED'); return e; end $$;
create or replace function public.depart_assignment(p_assignment_id uuid,p_odometer numeric) returns public.assignments language plpgsql security definer set search_path=public as $$ declare r public.assignments; begin if p_odometer is null or p_odometer < 0 then raise exception 'Invalid odometer'; end if; select a.* into r from public.assignments a join public.executors x on x.id=a.executor_id where a.id=p_assignment_id and a.status='CONFIRMED' and x.user_id=auth.uid() for update; if r.id is null then raise exception 'Invalid task state'; end if; if not exists(select 1 from public.execution where assignment_id=p_assignment_id and sj_confirmed_at is not null) then raise exception 'Surat Jalan must be confirmed'; end if; update public.execution set odometer_awal=p_odometer,odometer_awal_at=now(),departed_at=now(),updated_at=now() where assignment_id=p_assignment_id; update public.assignments set status='IN_PROGRESS',updated_at=now() where id=p_assignment_id returning * into r; return r; end $$;
create or replace function public.arrive_assignment(p_assignment_id uuid) returns public.assignments language plpgsql security definer set search_path=public as $$ declare r public.assignments; begin select a.* into r from public.assignments a join public.executors x on x.id=a.executor_id where a.id=p_assignment_id and a.status='IN_PROGRESS' and x.user_id=auth.uid() for update; if r.id is null then raise exception 'Invalid task state'; end if; update public.execution set arrived_at=now(),updated_at=now() where assignment_id=p_assignment_id; update public.assignments set status='ARRIVED',updated_at=now() where id=p_assignment_id returning * into r; return r; end $$;
create or replace function public.complete_assignment(p_assignment_id uuid,p_odometer numeric) returns public.assignments language plpgsql security definer set search_path=public as $$ declare r public.assignments; begin if p_odometer is null or p_odometer < 0 then raise exception 'Invalid odometer'; end if; select a.* into r from public.assignments a join public.executors x on x.id=a.executor_id where a.id=p_assignment_id and a.status='ARRIVED' and x.user_id=auth.uid() for update; if r.id is null then raise exception 'Invalid task state'; end if; update public.execution set odometer_akhir=p_odometer,odometer_akhir_at=now(),completed_at=now(),updated_at=now() where assignment_id=p_assignment_id; update public.assignments set status='COMPLETED',updated_at=now() where id=p_assignment_id returning * into r; return r; end $$;
revoke all on function public.confirm_assignment(uuid) from public; grant execute on function public.confirm_assignment(uuid) to authenticated;
revoke all on function public.confirm_surat_jalan(uuid) from public; grant execute on function public.confirm_surat_jalan(uuid) to authenticated;
revoke all on function public.depart_assignment(uuid,numeric) from public; grant execute on function public.depart_assignment(uuid,numeric) to authenticated;
revoke all on function public.arrive_assignment(uuid) from public; grant execute on function public.arrive_assignment(uuid) to authenticated;
revoke all on function public.complete_assignment(uuid,numeric) from public; grant execute on function public.complete_assignment(uuid,numeric) to authenticated;
